{"name": "Обновление данных пользователя без авторизации", "status": "passed", "description": "Тест проверяет, что при обновлении данных без авторизации возвращается ошибка 401", "steps": [{"name": "Попытка обновления имени без авторизации", "status": "passed", "start": 1729422907713, "stop": 1729422907941}, {"name": "Попытка обновления email без авторизации", "status": "passed", "start": 1729422907941, "stop": 1729422908048}, {"name": "Попытка обновления пароль без авторизации", "status": "passed", "start": 1729422908048, "stop": 1729422908154}], "start": 1729422907713, "stop": 1729422908155, "uuid": "3fcc0dde-377b-4e48-b53d-eae11fd2b80c", "historyId": "07ab88a5cef2592fab96280bbd02d941", "testCaseId": "07ab88a5cef2592fab96280bbd02d941", "fullName": "tests.test_update_user.TestUpdateUser#test_update_user_unauthorized", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_update_user"}, {"name": "subSuite", "value": "TestUpdateUser"}, {"name": "host", "value": "NikashaXD"}, {"name": "thread", "value": "7516-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_update_user"}]}